### ISSUE TITLE
Create QR online instead of delegate to QR App

### ISSUE THREAD

**Issue by StefMa** [marcosdiez/shareviahttp#10]
Like descripted in [this todo](https://github.com/marcosdiez/shareviahttp/blob/master/ShareViaHttp/app/src/main/java/com/MarcosDiez/shareviahttp/activities/BaseActivity.java#L115) we should made a QR code online and show it on its own activity.

**Comment by StefMa** [comment]
Or we can use zxing jar lib to create codes. Maybe better than online requests. 
How to is here: http://stackoverflow.com/a/30529128

**Comment by marcosdiez** [comment]
hi

I am against creating a qrcode online. It will increase the latency, add 
more moving parts to the app  and make the app need internet to work.

I am not sure if adding the jar worth it. I am not against it, but I 
don't think it worth the time. If you write the code, I would not mind 
merging, though.

Marcos Diez

**Comment by rugk** [comment]
Please never user online services to create QR codes. This destroys any privacy and security and makes it slower or in some cases (offline, LAN only) even impossible to use the app at all.

**Comment by marcosdiez** [comment]
Make sense!

**Comment by marcosdiez** [comment]
Now if the user tries to create a QR code and does not have a barcode scanner, the user will see a toast saying "please download the barcode scanner" and will be sent to the barcode scanner google play page
