### ISSUE TITLE
[bug] Change IP radio button doesn't update

### ISSUE THREAD

**Issue by ghost** [marcosdiez/shareviahttp#15]
The change IP screen always shows the radio button of the first option checked regardless of which IP configuration is current.

**Comment by marcosdiez** [comment]
So.... One actually does not "change" the IP. Your device has a lot of IPs and my app uses some heuristic to find out which is the "best" IP. If you click on the button it does not change the IP, it will just show a different IP on your screen. It's not supposed to save either.
