### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#34]
Would be nice if the server supports TLS.

This would include things like:
- a further port setting for TLS
- allowing the user to disable either http or https (e.g. to have only https allowed)
- creating per default a self signed x.509 cert... for the server
- allowing the user to upload his own cert/key
- during the share view, show the certs fingerprint and DN in the main view (so that users can check)
- also show (generally) whether files are served via http, https or both

**Comment by marcosdiez** [comment]
check answer to issue #35
