### ISSUE TITLE
cosmetic: don't call the share target "Share via HTTP"

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#36]
When I have an application e.g. the gallery and select files... and then click on share,... it shows me "Share via HTTP"...
But it's already long clear, that I'm sharing, since I clicked the share button... ;-)

So perhaps just call the registered target for the share operation:
"HTTP/S"... or "HTTP/S Server" or so.

**Comment by marcosdiez** [comment]
I like the name. I'll keep it. Sorry.
