### ISSUE TITLE
"share folder button" easily let's one zip huge amounts of data

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#37]
Hey.

When I e.g. share a single image at some path in the phone... then comes the main view of the app with the "share folder" button.
When I click that it goes from e.g.
file:///storage/emulated/0/DCIM/foo.jpg
to
file:///storage/emulated/0/DCIM/

When I click it again, it's already at:
file:///storage/emulated/0
and so on, always going one level up.

So IMO that button is a bit dangerous... as one easily shares (and zips) huge amounts of files.

Perhaps one should rather require the user to really select all these folders via some "file explorer" app and have them sent/shared to/via your app?

btw: The most recent URI RFCs allow the use of
file:/path/to/file
It's no longer necessary (though still allowed,... to do the triple-/)

**Comment by marcosdiez** [comment]
That's not a bug, it's a feature. You can make a backup of your whole internal memory with a few clicks.
Which other app allows you do to that ?

Why should my app prevent you from doing something that does not cause you to lose data ?
The worst possible thing that could happen is that it would send too much data and drain your battery/fill the HD space of the target device. I don't see that as a problem.
Trying to arbitrarily prevent the user from doing what s/he wanted is much worse.

**Comment by calestyo** [comment]
The "few clicks" sound rather concerning here for me... especially when the button is also shown when the user explicitly just shared a number fo files, via the share button.

This easily ends up in creating one huge zip file of the whole phone,... likely including all kinds of locally stored app data many of them possibly writing sensitive data like passwords rather unsecured on the SD/internal storage.

And I haven't said that you should generally disallow it ;-) ... a user could still go to some file explorer app, navigate up to the root, select this, and click share =)
