### ISSUE TITLE
Automatically turn ON mobile hotspot after picking file

### ISSUE THREAD

**Issue by jerryn70** [marcosdiez/shareviahttp#45]
It will be more easy if the app automatically turn OFF connected wifi/mobile data connection and turn ON mobile hotspot after we pick a file for transfer. Like other apps shareit , super beam etc

**Comment by StefMa** [comment]
That is not the idea of shareviahttp.
You can connect to wifi while others are connected to the same wifi.
You don't need to connect to the sender directly...
