### ISSUE TITLE
Copy of your app on the Play Store

### ISSUE THREAD

**Issue by Poussinou** [marcosdiez/shareviahttp#46]
Hi @marcosdiez 

I found [this app](https://play.google.com/store/apps/details?id=com.ShareOne.FileTransferandShare) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under BSD license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app and a link to it.

**Comment by StefMa** [comment]
Wow. Thank you for the report!
You should definitive tell Google about it.. Shitty scammers -.-

2017-12-29 18:06 GMT+01:00 Poussinou <notifications@github.com>:

**Comment by Poussinou** [comment]
I cannot do it by myself. To fill the DMCA takedown request, you have to be the owner of the app, something I'm not^^ I hope marcosdiez will do it :)

**Comment by jerryn70** [comment]
Why you closed this ?

There are more https://play.google.com/store/apps/details?id=com.openapps.fileshipper

https://play.google.com/store/apps/details?id=com.navan.shareviahttp
