### ISSUE TITLE
[feature request] set auto ip to local adress if connected to wlan

### ISSUE THREAD

**Issue by freerider123** [marcosdiez/shareviahttp#55]
using shareviahttp in wlan requires two manual clicks to change the ip adress of the webserver.
it would be nice, if local ip gets selected automatically when device is connected to wlan.
in a prior version this was the case.
if it isn't practical anymore, perhaps an option for "preferred ip adress type" or similar could be added.

**Comment by mnalis** [comment]
You do not need to change IP address at all, it always listens on all IP addresses (in 2.0.8 at least).  `Change IP` in the menu probably should be  renamed to `Show IP` to make this clearer, though.
